export default{
    RegisterAPI:"http://tutorials.codebetter.in:3000/auth/doctor/save",
    LoginAPI:"http://tutorials.codebetter.in:3000/auth/login",
    RecptionSave:" http://tutorials.codebetter.in:3000/api/reception/save",
    ReceptionDetails:"http://tutorials.codebetter.in:3000/api/reception/lists",
    PatientDetails:"http://tutorials.codebetter.in:3000/api/patient/list",
    ReceptionDelete:" http://tutorials.codebetter.in:3000/api/reception/delete/",
    UpdateReception:" http://tutorials.codebetter.in:3000/api/reception/updateReception/",
    patappdone:"http://tutorials.codebetter.in:3000/api/patient/done/",
    patappundo:" http://tutorials.codebetter.in:3000/api/patient/undo/",
    AddPatient:"http://tutorials.codebetter.in:3000/api/patient/addpatient",
    PatListRecp:"http://tutorials.codebetter.in:3000/api/patient/lists",
    patientDeletebyR :"http://tutorials.codebetter.in:3000/api/patient/delete/",
    patientupdatebyR :"http://tutorials.codebetter.in:3000/api/patient/update/",
}   